### ISSUE TITLE
GetClrType "Sequence contains no matching element" in LazyEntityGraph.EntityFramework.MetadataProperties

### ISSUE THREAD

**Issue by dhazel** [dbroudy/LazyEntityGraph#7] opened 2018-05-14 18:19 UTC
EntityFramework version 6
LazyEntityGraph version 2

Thanks for the great work!

When running the following customization per the documentation:

    var entityFrameworkCustomization = new LazyEntityGraphCustomization(
            ModelMetadataGenerator.LoadFromEdmxContext<MyContextType>("MyContextName"));

I am getting an error: "Sequence contains no matching element".

This is happening in `LazyEntityGraph.EntityFramework.MetadataProperties.GetClrType()` when the code is unable to find a metadata property with a name of `http://schemas.microsoft.com/ado/2013/11/edm/customannotation:ClrType`.

Am I doing something wrong? Or perhaps the loading from edmx is broken? Either way, a clearer error message would be nice. I am guessing someone with more LazyEntityGraph experience than I will say, "oh, the problem is obvious!"

**Comment by dbroudy** [comment] 2018-05-14 18:46
My initial thought is that there's some aspect of your entity model that isn't supported correctly by this library. There's so much possible variation in models that exist in the wild, it's hard to cover every scenario with the simple model used in our unit tests. However it's very much my intent to cover any model that EF supports. While the unit tests also don't cover loading from edmx files, there's very little code that's unique to that and to the best of my knowledge, it should be working.

Can you provide your edmx file or anything that might be unique about your model? Is this something that just started happening with newer versions?

**Comment by dhazel** [comment] 2018-05-14 19:42
This happened as well when I tried the 1.x version a few months ago.
I can't share my edmx file, but I will make some time to see if I can reproduce the problem with a smaller edmx file that I can share.

**Comment by dhazel** [comment] 2018-05-14 23:53
I recreated the problem with a small sample database and the default settings to generate the edmx off of the database. Everything is default.

Below is my edmx (as a txt so it would upload to github).

[Model1.edmx.txt](https://github.com/dbroudy/LazyEntityGraph/files/2002969/Model1.edmx.txt)

**Comment by dbroudy** [comment] 2018-05-15 14:58
Thanks David, yes, easy to reproduce. I haven't used edmx much, but it seems like the ClrType attribute is missing from the tool generated files, though it can be added manually to the xml and it's present in the cached edmx that the code first approach generates. I was hoping that the process of resolving a type when loading the model would add the custom attributes to the metadata, but that does not appear to be the case.

I'll have to look into some other approaches, but it doesn't looks like edmx is functional right now.

**Comment by dbroudy** [comment] 2018-07-07 00:40
@alexfoxgill do you happen to remember any details from when you built the EDMX support in LazyEntityGraph? It tests out ok with an EDMX from the code first tests, but not with one build using the Visual Studio tooling. Maybe the tooling changed, or this isn't something that's being commonly used?

**Comment by alexfoxgill** [comment] 2018-07-09 13:41
Here's the SO post I used to get the CLR type from an EntityType https://stackoverflow.com/questions/22999330/mapping-from-iedmentity-to-clr - looks like EF6 might have made some changes (the EDMX stuff was written against EF5), perhaps [this answer](https://stackoverflow.com/a/23013196/1860652) might help

**Comment by dbroudy** [comment] 2018-07-12 15:30
Thanks Alex, that helps a lot.

**Comment by ika-microsoft** [comment] 2019-02-11 12:19
Ran into the same issue. Any plans to fix this bug?

**Comment by dbroudy** [comment] 2019-02-13 18:20
@ika-microsoft Unfortunately it's a little bigger than just a bug, it looks like there's a new metadata model in EF6 and moving to that will fix this. I believe it's similar, but less well documented, to the metadata model in EF Core, so it should be a similar implementation.

I don't personally use EDMX, so I haven't gotten around to taking a deeper look at this.

**Closed as completed** 2020-07-02 04:04 UTC
